"""Robot asset configurations."""


from .g1_wuji import (
    DOORMAN_ALL_DOF_NAMES,
    DOORMAN_CONTROL_GROUPS,
    DOORMAN_LEFT_ARM_DOF_NAMES,
    DOORMAN_LEFT_HAND_DOF_NAMES,
    DOORMAN_LOWER_BODY_DOF_NAMES,
    DOORMAN_RIGHT_ARM_DOF_NAMES,
    DOORMAN_RIGHT_HAND_DOF_NAMES,
    G1_WUJI_ASSET_DIR,
    G1_WUJI_CFG,
    G1_WUJI_FREE_BASE_CFG,
    G1_WUJI_USD_PATH,
)
